<?php
/**
 * @file
 * Code for the Ktopic feature.
 */

include_once 'ktopic.features.inc';

include_once 'ktopic.field.inc';

/**
 * Return list of ktopic type options.
 */
function ktopic_type_options() {
  $vocab = taxonomy_vocabulary_machine_name_load('ktype');
  $terms = taxonomy_get_tree($vocab->vid);
  $options = array();
  foreach ($terms as $term) {
    $options[$term->tid] = $term->name;
  }

  return $options;
}

/**
 * Load ktopic entity, node.
 */
function ktopic_load($name) {
  $conds[] = array(
    'column' => 'machine',
    'value' => $name,
    'operator' => '=',
  );
  $ids = KtoolsEntityField::queryEntities(KTOPIC_FIELD_NAME, $conds, 'node');

  return node_load(reset($ids));
}
